name: Demo

on:
  # webhook event#
  push:
    branches:
      - main
      - Task/*
      - feat/*
  pull_request:
    branches:
      - main
  # schedule event
  schedule:
    - cron: 0 12 * * *  
    - cron: 0 9 * * 0  
  issues:
    types: 
      - closed
      - opened
      
  # manual event
  workflow_dispatch:
    inputs:
      areYouFeelingGood: 
        description: "Are you good enough ?"


env:
  MY_VAR: Ashish
  MY_GREETINGS: Hello
  
jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say_hello
        run: echo "HI I am here bro !!! in GITHUB ACTIONS"
  Job2:
    runs-on: ubuntu-latest
    needs: [Greeting]
    steps:
      - name: Step2
        run: echo "This step I belive in GA world from Greeting !!!"
      - name: Step3
        if: ${{ inputs.areYouFeelingGood }}
        run: echo "I am great bro here very confusing !!!"
      - name: Step4
        if: ${{ !inputs.areYouFeelingGood }}
        run: echo "I am not good here bro.. need escape from GA world.. !!!"
      - name: Step5
        run: echo my greeting code is ${{env.MY_GREETINGS}} from ${{env.MY_VAR}} 
